"""
Portfolio Simulator

This module is responsible for simulating portfolio performance by executing
trading signals generated by the Strategy Engine.

Responsibilities
----------------
- Execute BUY, SELL and HOLD signals.
- Track portfolio state (cash, holdings, portfolio value).
- Record completed trades.
- Produce a portfolio history and simulation summary.

The simulator intentionally remains independent of:
- Market data acquisition
- Indicator calculations
- Strategy generation
- Performance analytics
"""

from dataclasses import dataclass
from typing import Any

import pandas as pd

from risk.manager import RiskManager
from risk.config import RiskConfig
from utils.logger import get_logger

logger = get_logger(__name__)


BUY = "BUY"
SELL = "SELL"
HOLD = "HOLD"

FLAT = "FLAT"
LONG = "LONG"


@dataclass
class SimulationResult:
    """
    Container for the results of a portfolio simulation.

    Attributes
    ----------
    portfolio_history : pd.DataFrame
        Portfolio state recorded for every trading day.

    trade_history : pd.DataFrame
        One row per completed trade.

    summary : dict[str, Any]
        High-level simulation summary.
    """

    portfolio_history: pd.DataFrame
    trade_history: pd.DataFrame
    summary: dict[str, Any]

@dataclass
class PortfolioState:
    """
    Represents the current state of the simulated portfolio.

    Attributes
    ----------
    cash : float
        Available cash balance.

    shares : int
        Number of shares currently held.

    position : str
        Current portfolio position.
        Valid values are "FLAT" and "LONG".
    """

    cash: float
    shares: int
    position: str

@dataclass
class OpenTrade:
    """
    Represents the currently open trade.
    """

    entry_date: pd.Timestamp
    entry_index: int
    entry_price: float
    shares: int
    highest_close: float

@dataclass
class CompletedTrade:
    """
    Represents a completed trade.
    """

    entry_date: pd.Timestamp
    exit_date: pd.Timestamp
    entry_price: float
    exit_price: float
    shares: int
    investment: float
    exit_value: float
    profit_loss: float
    return_pct: float
    holding_period: int
    exit_reason: str = "signal"
    stop_loss_price: float | None = None
    take_profit_price: float | None = None


def simulate_portfolio(
    df: pd.DataFrame,
    initial_capital: float = 100000,
    risk_config: RiskConfig | None = None,
) -> SimulationResult:
    """
    Simulate portfolio performance using trading signals.

    Parameters
    ----------
    df : pd.DataFrame
        Standardized market data containing a 'Close' column and a
        'Signal' column produced by the Strategy Engine.

    initial_capital : float, default=100000
        Starting capital available for trading.

    Returns
    -------
    SimulationResult
        Object containing portfolio history, completed trade history
        and a high-level simulation summary.
    """

    logger.info("Starting portfolio simulation.")

    _validate_input(df, initial_capital)

    portfolio = _initialize_portfolio(initial_capital)
    portfolio_value = initial_capital
    risk_manager = RiskManager(risk_config)

    logger.debug(
        "Initial portfolio state: "
        f"Cash={portfolio.cash}, "
        f"Shares={portfolio.shares}, "
        f"Position={portfolio.position}"
    )

    open_trade: OpenTrade | None = None
    completed_trades: list[CompletedTrade] = []

    portfolio_history = df.copy()

    # Store portfolio history in Python lists during the simulation.
    cash_history = []
    shares_history = []
    holdings_value_history = []
    portfolio_value_history = []
    position_history = []

    for row_number, row in enumerate(
        portfolio_history.itertuples()
    ):
        index = row.Index
        signal = row.Signal
        close_price = row.Close

        if open_trade is not None:
            open_trade.highest_close = max(
                open_trade.highest_close,
                close_price,
            )

        logger.debug(
            f"Processing {index}: "
            f"Signal={signal}, "
            f"Close={close_price}"
        )

        open_trade, completed_trade = _evaluate_risk_and_signal(
            signal=signal,
            current_date=index,
            current_index=row_number,
            close_price=close_price,
            portfolio=portfolio,
            open_trade=open_trade,
            risk_manager=risk_manager,
        )

        if completed_trade is not None:
            completed_trades.append(completed_trade)

        holdings_value, portfolio_value = _update_portfolio_state(
            portfolio,
            close_price,
        )

        # Record the current state in Python lists.
        # The portfolio itself is still updated every iteration.
        cash_history.append(portfolio.cash)
        shares_history.append(portfolio.shares)
        holdings_value_history.append(holdings_value)
        portfolio_value_history.append(portfolio_value)
        position_history.append(portfolio.position)

    # Write the completed portfolio history to the DataFrame once
    # after the simulation loop.
    portfolio_history["Cash"] = cash_history
    portfolio_history["Shares"] = shares_history
    portfolio_history["Holdings Value"] = holdings_value_history
    portfolio_history["Portfolio Value"] = portfolio_value_history
    portfolio_history["Position"] = position_history

    trade_history = pd.DataFrame(
        [vars(trade) for trade in completed_trades]
    )

    summary = _create_summary(
        portfolio=portfolio,
        initial_capital=initial_capital,
        final_portfolio_value=portfolio_value,
        completed_trades=completed_trades,
    )

    logger.info("Portfolio simulation completed.")

    return SimulationResult(
        portfolio_history=portfolio_history,
        trade_history=trade_history,
        summary=summary,
    )


def _validate_input(
    df: pd.DataFrame,
    initial_capital: float,
) -> None:
    """
    Validate inputs supplied to the Portfolio Simulator.

    Parameters
    ----------
    df : pd.DataFrame
        Input market data.

    initial_capital : float
        Initial portfolio capital.

    Raises
    ------
    TypeError
        If the supplied data is not a DataFrame.

    ValueError
        If the DataFrame is empty, required columns are missing,
        invalid signals are present, or initial capital is invalid.
    """

    if not isinstance(df, pd.DataFrame):
        raise TypeError("Input data must be a pandas DataFrame.")

    if df.empty:
        raise ValueError("Input DataFrame cannot be empty.")

    required_columns = {"Close", "Signal"}
    missing_columns = required_columns - set(df.columns)

    if missing_columns:
        raise ValueError(
            f"Missing required columns: {sorted(missing_columns)}"
        )

    valid_signals = {"BUY", "SELL", "HOLD"}

    invalid_signals = (
        set(df["Signal"].dropna().unique()) - valid_signals
    )

    if invalid_signals:
        raise ValueError(
            f"Invalid signal values found: {sorted(invalid_signals)}"
        )

    if initial_capital <= 0:
        raise ValueError("Initial capital must be greater than zero.")
    
def _initialize_portfolio(
    initial_capital: float,
) -> PortfolioState:
    """
    Initialize the portfolio state.

    Parameters
    ----------
    initial_capital : float
        Starting capital available for trading.

    Returns
    -------
    PortfolioState
        Initialized portfolio state.
    """

    logger.debug("Initializing portfolio state.")

    return PortfolioState(
        cash=initial_capital,
        shares=0,
        position=FLAT,
    )

def _update_portfolio_state(
    portfolio: PortfolioState,
    close_price: float,
) -> tuple[float, float]:
    """
    Calculate the current portfolio valuation.

    Parameters
    ----------
    portfolio : PortfolioState
        Current portfolio state.

    close_price : float
        Closing price for the current trading day.

    Returns
    -------
    tuple[float, float]
        Holdings value and total portfolio value.
    """

    holdings_value = portfolio.shares * close_price
    portfolio_value = portfolio.cash + holdings_value

    return holdings_value, portfolio_value

def _evaluate_risk_and_signal(
    signal: str,
    current_date: pd.Timestamp,
    current_index: int,
    close_price: float,
    portfolio: PortfolioState,
    open_trade: OpenTrade | None,
    risk_manager: RiskManager,
) -> tuple[OpenTrade | None, CompletedTrade | None]:
    """
    Evaluate the risk manager first, then process the strategy signal.
    """

    if open_trade is not None and risk_manager.should_stop(
        entry_price=open_trade.entry_price,
        current_price=close_price,
        peak_price=open_trade.highest_close,
    ):
        logger.debug(
            "Stop-loss triggered for open trade at %s.",
            current_date,
        )
        return _execute_stop_loss(
            portfolio=portfolio,
            open_trade=open_trade,
            current_date=current_date,
            current_index=current_index,
            close_price=close_price,
            risk_manager=risk_manager,
        )

    if open_trade is not None and risk_manager.should_take_profit(
        entry_price=open_trade.entry_price,
        current_price=close_price,
    ):
        logger.debug(
            "Take-profit triggered for open trade at %s.",
            current_date,
        )
        return _execute_take_profit(
            portfolio=portfolio,
            open_trade=open_trade,
            current_date=current_date,
            current_index=current_index,
            close_price=close_price,
            risk_manager=risk_manager,
        )

    if signal == BUY:
        new_trade = _execute_buy(
            portfolio,
            current_date,
            current_index,
            close_price,
        )
        if new_trade is not None:
            open_trade = new_trade
        return open_trade, None

    elif signal == SELL:
        open_trade, completed_trade = _execute_sell(
            portfolio,
            open_trade,
            current_date,
            current_index,
            close_price,
        )
        return open_trade, completed_trade

    return open_trade, None

def _execute_buy(
    portfolio: PortfolioState,
    current_date: pd.Timestamp,
    current_index: int,
    close_price: float,
) -> OpenTrade | None:
    """
    Execute a BUY order.

    The simulator purchases the maximum number of whole shares
    possible using all available cash.

    BUY signals are ignored while already holding a position.
    """

    if portfolio.position == LONG:
        logger.debug(
            "BUY signal ignored because portfolio is already LONG."
        )
        return None

    shares_to_buy = int(portfolio.cash // close_price)

    if shares_to_buy == 0:
        logger.debug(
            "BUY signal ignored because available cash is insufficient."
        )
        return None

    investment = shares_to_buy * close_price

    portfolio.cash -= investment
    portfolio.shares = shares_to_buy
    portfolio.position = LONG

    logger.debug(
        "BUY executed: "
        f"{shares_to_buy} shares "
        f"at {close_price:.2f}"
    )

    return OpenTrade(
        entry_date=current_date,
        entry_index=current_index,
        entry_price=close_price,
        shares=shares_to_buy,
        highest_close=close_price,
    )

def _execute_stop_loss(
    portfolio: PortfolioState,
    open_trade: OpenTrade,
    current_date: pd.Timestamp,
    current_index: int,
    close_price: float,
    risk_manager: RiskManager,
) -> tuple[OpenTrade | None, CompletedTrade | None]:
    """
    Close an open trade because the stop-loss threshold was reached.
    """

    exit_value = open_trade.shares * close_price

    portfolio.cash += exit_value
    portfolio.shares = 0
    portfolio.position = FLAT

    investment = open_trade.entry_price * open_trade.shares
    profit_loss = exit_value - investment
    return_pct = (profit_loss / investment) * 100

    holding_period = current_index - open_trade.entry_index
    stop_loss_price = risk_manager.get_stop_loss_price(
        open_trade.entry_price,
        peak_price=open_trade.highest_close,
    )

    completed_trade = CompletedTrade(
        entry_date=open_trade.entry_date,
        exit_date=current_date,
        entry_price=open_trade.entry_price,
        exit_price=close_price,
        shares=open_trade.shares,
        investment=investment,
        exit_value=exit_value,
        profit_loss=profit_loss,
        return_pct=return_pct,
        holding_period=holding_period,
        exit_reason="stop_loss",
        stop_loss_price=stop_loss_price,
    )

    logger.debug("Stop-loss executed: Position closed.")

    return None, completed_trade


def _execute_take_profit(
    portfolio: PortfolioState,
    open_trade: OpenTrade,
    current_date: pd.Timestamp,
    current_index: int,
    close_price: float,
    risk_manager: RiskManager,
) -> tuple[OpenTrade | None, CompletedTrade | None]:
    """
    Close an open trade because the take-profit threshold was reached.
    """

    exit_value = open_trade.shares * close_price

    portfolio.cash += exit_value
    portfolio.shares = 0
    portfolio.position = FLAT

    investment = open_trade.entry_price * open_trade.shares
    profit_loss = exit_value - investment
    return_pct = (profit_loss / investment) * 100

    holding_period = current_index - open_trade.entry_index
    take_profit_price = risk_manager.get_take_profit_price(
        open_trade.entry_price,
    )

    completed_trade = CompletedTrade(
        entry_date=open_trade.entry_date,
        exit_date=current_date,
        entry_price=open_trade.entry_price,
        exit_price=close_price,
        shares=open_trade.shares,
        investment=investment,
        exit_value=exit_value,
        profit_loss=profit_loss,
        return_pct=return_pct,
        holding_period=holding_period,
        exit_reason="take_profit",
        take_profit_price=take_profit_price,
    )

    logger.debug("Take-profit executed: Position closed.")

    return None, completed_trade


def _execute_sell(
    portfolio: PortfolioState,
    open_trade: OpenTrade | None,
    current_date: pd.Timestamp,
    current_index: int,
    close_price: float,
) -> tuple[OpenTrade | None, CompletedTrade | None]:
    """
    Execute a SELL order.

    Returns
    -------
    tuple
        Updated open trade and completed trade (if any).
    """

    if portfolio.position == FLAT or open_trade is None:
        logger.debug(
            "SELL signal ignored because portfolio is already FLAT."
        )
        return open_trade, None

    exit_value = portfolio.shares * close_price

    portfolio.cash += exit_value
    portfolio.shares = 0
    portfolio.position = FLAT

    investment = open_trade.entry_price * open_trade.shares
    profit_loss = exit_value - investment
    return_pct = (profit_loss / investment) * 100

    holding_period = (
        current_index - open_trade.entry_index
    )

    completed_trade = CompletedTrade(
        entry_date=open_trade.entry_date,
        exit_date=current_date,
        entry_price=open_trade.entry_price,
        exit_price=close_price,
        shares=open_trade.shares,
        investment=investment,
        exit_value=exit_value,
        profit_loss=profit_loss,
        return_pct=return_pct,
        holding_period=holding_period,
        exit_reason="signal",
        stop_loss_price=None,
    )

    logger.debug(
        "SELL executed: Position closed."
    )

    return None, completed_trade

def _create_summary(
    portfolio: PortfolioState,
    initial_capital: float,
    final_portfolio_value: float,
    completed_trades: list[CompletedTrade],
) -> dict[str, Any]:
    """
    Create a high-level summary of the portfolio simulation.

    Parameters
    ----------
    portfolio : PortfolioState
        Final portfolio state.

    initial_capital : float
        Starting capital for the simulation.

    final_portfolio_value : float
        Portfolio value at the end of the simulation.

    completed_trades : list[CompletedTrade]
        List of completed trades.

    Returns
    -------
    dict[str, Any]
        Summary of the simulation results.
    """

    logger.debug("Creating simulation summary.")

    return {
        "initial_capital": initial_capital,
        "final_portfolio_value": final_portfolio_value,
        "cash": portfolio.cash,
        "shares_held": portfolio.shares,
        "position": portfolio.position,
        "open_position": portfolio.position == LONG,
        "completed_trade_count": len(completed_trades),
    }